// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaxC4NbSF63q4MXqB9Xp55mzhpAexwMvM',
    appId: '1:570265938955:web:b8e3fa997e89ef4049ab0e',
    messagingSenderId: '570265938955',
    projectId: 'gym-system-5e7e5',
    authDomain: 'gym-system-5e7e5.firebaseapp.com',
    storageBucket: 'gym-system-5e7e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBDyYVP6b998G4rG3R6_aVvnDTrcEaFM',
    appId: '1:570265938955:android:65fe732325f9f1ab49ab0e',
    messagingSenderId: '570265938955',
    projectId: 'gym-system-5e7e5',
    storageBucket: 'gym-system-5e7e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0j15OizAsCFdDlPGwNqgktFenBDJF-Aw',
    appId: '1:570265938955:ios:911d6df39f78193c49ab0e',
    messagingSenderId: '570265938955',
    projectId: 'gym-system-5e7e5',
    storageBucket: 'gym-system-5e7e5.firebasestorage.app',
    iosClientId: '570265938955-0g0dphjbholcji2fp6t6bjqb3okappq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaxC4NbSF63q4MXqB9Xp55mzhpAexwMvM',
    appId: '1:570265938955:web:58d2f2c4797057cb49ab0e',
    messagingSenderId: '570265938955',
    projectId: 'gym-system-5e7e5',
    authDomain: 'gym-system-5e7e5.firebaseapp.com',
    storageBucket: 'gym-system-5e7e5.firebasestorage.app',
  );
}
